# Generated by Django 4.1.1 on 2022-09-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50, verbose_name="Título")),
                (
                    "tempo_preparo",
                    models.CharField(
                        help_text="Ex: 30 minutos",
                        max_length=50,
                        verbose_name="Tempo de preparo",
                    ),
                ),
                (
                    "rende_ate",
                    models.CharField(
                        help_text="Ex: 03 porções",
                        max_length=50,
                        verbose_name="Rende até",
                    ),
                ),
                (
                    "ingredientes",
                    models.TextField(
                        help_text="Informe os ingredientes e suas quantidades"
                    ),
                ),
                (
                    "modo_preparo",
                    models.TextField(
                        help_text="Descreva o modo de preparo da receita",
                        verbose_name="Modo de preparo",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="imagem"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="post.categoria"
                    ),
                ),
            ],
        ),
    ]
