# Generated by Django 4.1.1 on 2022-09-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="ingredientes",
            field=models.TextField(
                help_text="Informe os ingredientes e suas quantidades."
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="modo_preparo",
            field=models.TextField(
                help_text="Descreva o modo de preparo da receita.",
                verbose_name="Modo de preparo",
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="rende_ate",
            field=models.CharField(
                help_text="Ex: 03 porções.", max_length=50, verbose_name="Rende até"
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="tempo_preparo",
            field=models.CharField(
                help_text="Ex: 30 minutos.",
                max_length=50,
                verbose_name="Tempo de preparo",
            ),
        ),
    ]
