# Generated by Django 4.1.1 on 2022-09-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_receita_ingredientes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="modo_de_preparo",
            field=models.TextField(
                default=1, help_text="Descreva o modo de preparo da receita."
            ),
            preserve_default=False,
        ),
    ]
