# Generated by Django 4.1.1 on 2022-09-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_receita_modo_de_preparo"),
    ]

    operations = [
        migrations.RemoveField(model_name="receita", name="modo_de_preparo",),
    ]
