# Generated by Django 4.1.1 on 2022-09-20 22:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_receita_modo_de_preparo"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="modo_de_preparo",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
