# Generated by Django 4.1.1 on 2022-09-22 13:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_receita_modo_preparoo"),
    ]

    operations = [
        migrations.RemoveField(model_name="receita", name="imagem",),
        migrations.RemoveField(model_name="receita", name="modo_preparoo",),
        migrations.AlterField(
            model_name="receita",
            name="modo_preparo",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
