# Generated by Django 4.1.1 on 2022-09-22 13:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_remove_receita_imagem_remove_receita_modo_preparoo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="ingredientes",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
