# Generated by Django 4.1.1 on 2022-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_receita_ingredientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita", name="ingredientes", field=models.TextField(),
        ),
    ]
