# Generated by Django 4.1.1 on 2022-09-22 14:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_alter_receita_ingredientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="ingredientes",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
