# Generated by Django 4.1.1 on 2022-09-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_alter_receita_ingredientes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita", old_name="ingredientes", new_name="ingredientess",
        ),
        migrations.RenameField(
            model_name="receita", old_name="modo_preparo", new_name="modo_de_preparo",
        ),
    ]
