# Generated by Django 4.1.1 on 2022-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0013_remove_receita_ingredientess_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
