# Generated by Django 4.1.1 on 2022-09-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0014_receita_imagem"),
    ]

    operations = [
        migrations.RemoveField(model_name="receita", name="imagem",),
    ]
