# Generated by Django 4.1.1 on 2022-09-26 14:26

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0015_remove_receita_imagem"),
    ]

    operations = [
        migrations.RemoveField(model_name="receita", name="ingredientes_da_receita",),
        migrations.RemoveField(model_name="receita", name="passo_a_passo",),
        migrations.AddField(
            model_name="receita",
            name="ingredientes",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receita",
            name="modo_de_preparo",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
