# Generated by Django 4.1.1 on 2022-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0016_remove_receita_ingredientes_da_receita_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="imagem"),
        ),
    ]
