# Generated by Django 4.1.1 on 2022-09-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0017_receita_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
