# Generated by Django 4.1.1 on 2022-09-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0018_receita_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="receita", name="slug",),
    ]
