# Generated by Django 4.1.1 on 2022-09-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0019_remove_receita_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="imagem"),
        ),
    ]
