# Generated by Django 4.1.1 on 2022-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0020_categoria_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
