# Generated by Django 4.1.1 on 2022-09-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0021_receita_publicada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="categoria",
            field=models.CharField(max_length=100),
        ),
    ]
